### ISSUE TITLE
Rework heed to be lightweight and simpler to maintain

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/heed#127]
- [x] Create a sub-crate for lmdb-sys in this repository, based on the `mdb.master.3` branch of LMDB.
- [x] Move from zerocopy to bytemuck (also related to licensing). https://github.com/meilisearch/heed/issues/82
- [ ] Be able to use `MDB_WRITEMAP` with heed to create databases. https://github.com/meilisearch/heed/pull/116
- [x] Remove the generic types of the `RoTxn` and `RwTxn`. https://github.com/meilisearch/heed/issues/94
- [ ] https://github.com/meilisearch/heed/issues/88. This is related to bytemuck. Don't forget to make `heed::Error: Send + Sync`.
- [x] Reintroduce a faster `Database::len` function. https://github.com/meilisearch/heed/issues/56
- [ ] Close all the issues/PRs that are related to MDBX as we no more support it and write about that in the README. https://github.com/meilisearch/heed/pull/125#issuecomment-1111910573
- [ ] Delete all of the branches that are not interesting anymore, and move from a `master` to a `main` branch.
- [ ] Document the safety issues with the unnamed database. https://github.com/meilisearch/heed/issues/40
- [ ] We should rework the usage of the `OwnedType` combined with `BEU32` types too!
